### ISSUE TITLE
Facing issues with sending rich notifications for ios

### ISSUE THREAD

**Issue by uday12kumar** [dreipol/django-scarface#23]
I have been trying to send rich notifications to ios, I have the extra payload which we have to send to apns to receive rich notifications.
But the ios device unable to detect whether the notifications is normal or rich notification.

Am I building the PushMessage correctly if not do let me know what to change thanks.

```
return PushMessage(
        context=json.dumps(data),
        context_id='none',
        has_new_content=True,
        message=alert,
        sound="default",
        badge_count=1,
        extra_payload={'mutable-content': True},
    )
```

**Comment by uday12kumar** [comment]
@J0hn5mith ^^

**Comment by melbic** [comment]
@uday12kumar  Did you find a solution to your problem?

**Comment by uday12kumar** [comment]
using scarface no. I am using boto for now

**Comment by melbic** [comment]
Ok. I will close this issue then. If you would like to implement it with Scarface, just reopen it and paste the dictionary from the device and what about it is wrong.
