### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by kennydude** [dreipol/django-scarface#24]
Django-scarface does not run properly on Django 2.0

ForeignKey's now require `on_delete` set on them [as the release notes state](https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0)

**Comment by melbic** [comment]
Hey @kennydude sorry for the late answer. If you would create a PR we would be happy to merge it. We still use this framework in production, but no further development is planned from us atm.
