### ISSUE TITLE
Message Trimming

### ISSUE THREAD

**Issue by philipplaeubli** [dreipol/django-scarface#4]
The current trim treshold too small. The best thing would probably be to remove the trimming anyway (or to add a warning).

**Comment by Dealers** [comment]
Thanks Philipp.

How can I Philipp remove the trimming?

Regards

Uzi Lumbroso

M +972-52-3330506

F  +972-9-7710184

uzi@dealers-app.com

Skype: uzport

Logo_(full).png 

 http://www.dealers-app.com/ www.dealers-app.com

The information contained in this document is proprietary of Dealers©. It contains confidential or privileged information, and is intended only for the use of the intended addressee thereof. If you are not the intended addressee, please be aware  that any use, disclosure, distribution and/or copying of this communication is strictly prohibited. If you receive this document or communication in error, please return it to Dealers© and delete it from your computer. Thank you. 

P Please consider the environment before printing this email

**Comment by melbic** [comment]
Please notice, that there still is a maximum payload length for push message.
For APNS prior iOS 8 it was 256 bytes, in iOS 8 and later it is 2 kBytes.
(https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW1)
For GCM I didn't check yet.

**Comment by philipplaeubli** [comment]
True, and also related:
http://aws.amazon.com/about-aws/whats-new/2013/06/18/amazon-sqs-announces-256KB-large-payloads/

**Comment by melbic** [comment]
@Dealers The method is called `trim_message` and is in `models.py`.

**Comment by Dealers** [comment]
Thanks. 

נשלח מה-iPhone שלי

‫ב-27 באפר׳ 2015, בשעה 09:47, ‏‏Samuel Bichsel ‏notifications@github.com כתב/ה:‬

**Comment by philipplaeubli** [comment]
Fixed with c99ef2b
